# Spring settings
spring:
  profiles:
    active: dev

# FTP settings
ftp:
  port: ${FTP_PORT}
  host: ${FTP_HOST}
  username: ${FTP_USERNAME}
  password: ${FTP_PASSWORD}
  connectTimeout: 60000
  dataTimeout: 60000
